export const Actions = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  QUANTITY_PRODUCT: "QUANTITY_PRODUCT",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_ONE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};
